version: "3"

services:

  postgis:
    build: db
    container_name: gnlpoaura_db
    volumes:
      - $PGDATA:/var/lib/postgresql/data
      - $PGLOG:/var/log/postgresql
    ports: 
      - $DBPORT:5432/tcp
    environment:
      - POSTGRES_USER=$DBUSER
      - POSTGRES_PASSWORD=$DBPASS
      - POSTGRES_DB=$DBNAME

