FROM ubuntu:bionic

RUN apt update ; apt install -y wget;\
    echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list;\
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -;\
    apt-get update;\
    apt-get -y postgresql-11 postgresql-11-postgis-2.5 postgresql-11-ogr-fdw postgresql-11-postgis-2.5-scripts;\
    systemctl restart postgresql;

VOLUME ["/etc/postgresql","/var/lib/postgresql","/var/log/postgresql"]
EXPOSE 5432

